## intro2Python

** shift+return **

In [1]:
3+5*4

23

In [3]:
weight_kg = 60

In [4]:
print(weight_kg)

60


In [5]:
weight_kg_text = 'weight in kilograms:'

In [6]:
print(weight_kg_text, weight_kg)

weight in kilograms: 60



** ESC+A / ESC+B **

In [1]:
import numpy

In [2]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
numpy      module    <module 'numpy' from '/so<...>kages/numpy/__init__.py'>


In [4]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [5]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [6]:
%whos

Variable   Type       Data/Info
-------------------------------
data       ndarray    60x40: 2400 elems, type `float64`, 19200 bytes
numpy      module     <module 'numpy' from '/so<...>kages/numpy/__init__.py'>
